version: "3.9"

services:
  server:
    build: ./server
    container_name: hashbrute-server
    working_dir: /app
    env_file:
      - ./server/.env
    networks:
      - hashbrute-net

  front:
    build: ./front
    container_name: hashbrute-front
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://nginx/api
    networks:
      - hashbrute-net

  nginx:
    image: nginx:1.27-alpine
    container_name: hashbrute-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front
      - server
    networks:
      - hashbrute-net

networks:
  hashbrute-net:
    driver: bridge
